version: '3.8'

services:
  mongo:
    image: mongo:4.2.1
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"

volumes:
  mongo_data:
